### ISSUE TITLE
Specifying globals

### ISSUE THREAD

**Issue by medialwerk** [markwainwright/atom-linter-coffee-variables#13]
Hello,
it would be nice to be able to set globals at the plugin config:
http://eslint.org/docs/user-guide/configuring#specifying-globals

Is it planned to add this feature in an upcoming version? :-)

**Comment by markwainwright** [comment]
Hiya @medialwerk, are you referring to comments that define globals for that file? If so, take a look at https://github.com/markwainwright/atom-linter-coffee-variables/issues/7 for how you can do this.

If you're talking about reading in a project-wide `.eslintrc` or similar, take a look at https://github.com/markwainwright/atom-linter-coffee-variables/issues/5 and let's continue the discussion there.

Thanks!
