### ISSUE TITLE
Error running CoffeeVariables TypeError: Cannot read property 'errors' of undefined

### ISSUE THREAD

**Issue by binarykitchen** [markwainwright/atom-linter-coffee-variables#19]
happens on latest version

![screen shot 2017-08-21 at 12 44 52](https://user-images.githubusercontent.com/177641/29499893-91b7e3e0-866e-11e7-8c18-fd212dc6675a.png)

**Comment by markwainwright** [comment]
Hi @binarykitchen. I can't reproduce this myself but I've just published `v0.8.2` with an attempted fix. Please feel free to re-open if you're still seeing this after updating. Cheers!
