### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by tanajilondhefidel** [markwainwright/atom-linter-coffee-variables#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.2
**Thrown From**: [linter-coffee-variables](https://github.com/markwainwright/atom-linter-coffee-variables) package 0.8.2

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /home/thinkitive/.atom/packages/linter-coffee-variables/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/linter-coffee-variables/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
```

### Non-Core Packages

```
atom-import-js 0.21.0 
linter-coffee-variables 0.8.2 
prettier-atom 0.58.0 
```

**Comment by markwainwright** [comment]
Hi there – I've published `1.0.0` which will hopefully fix this by upgrading `atom-package-deps`. Feel free to re-open if you're still seeing issues after updating.
