### ISSUE TITLE
Does not detect unused variables

### ISSUE THREAD

**Issue by binarykitchen** [markwainwright/atom-linter-coffee-variables#21]
<img width="374" alt="Screen Shot 2020-01-10 at 13 02 43" src="https://user-images.githubusercontent.com/177641/72114777-827de600-33a9-11ea-9bb1-8076a5f8a8ce.png">

I expect these to be underlined in red.

Also have ticket the debug option under settings but can't find output debug anywhere.

**Comment by binarykitchen** [comment]
<img width="753" alt="Screen Shot 2020-01-10 at 13 05 00" src="https://user-images.githubusercontent.com/177641/72114859-d38dda00-33a9-11ea-8b10-639e3c51b28e.png">

For the record these are the coffeescript related packages I've installed.

**Comment by markwainwright** [comment]
Hi Michael – I've published `1.0.0` which should fix this by adding compatibility with `linter` v2. Feel free to re-open if you're still seeing issues after updating.

**Comment by binarykitchen** [comment]
Yep, works now, thanks
