### ISSUE TITLE
Bug - variable not used

### ISSUE THREAD

**Issue by MocanuMarius** [markwainwright/atom-linter-coffee-variables#3]
As you can see, a very big bug and the reason i uninstalled this. Doesn't work if i put it on the next line either.

![image](https://cloud.githubusercontent.com/assets/6069369/10879250/855fb1be-815b-11e5-84ae-fa1850ad7004.png)

**Comment by markwainwright** [comment]
Hi there, thanks for the info.

This is a bug that I'm aware of. When there is a `defined but never used` error, the plugin highlights the first use of that variable in the file – not necessarily the correct one.

In your case you likely have a place where `reply` is defined without being used _later in the same file_. The error is correct but the highlighted position is not.

I've made #4 with a minimal reproduction case and I'll try my best to get this fixed soon.

**Comment by MocanuMarius** [comment]
Alrighty then, good luck with that, i don't have time to dive into the code myself. Thank you

**Comment by markwainwright** [comment]
I just released v0.4.2 which should fix this, so I'll close this issue. If you still have problems, please feel free to re-open it. Thanks!

**Comment by MocanuMarius** [comment]
Good job Mark, thank you !
