### ISSUE TITLE
Option to load configuration

### ISSUE THREAD

**Issue by nmccready** [markwainwright/atom-linter-coffee-variables#5]
Thanks for starting this project!

Instead of modifying the settings in atom.io I think the package should pick up the settings from a projects .eslintrc.

**Comment by markwainwright** [comment]
@nmccready: I agree. While the use of ESLint doesn't need to be known to the user, if they _do_ have a config file for it, the plugin should definitely use it. I 100% agree that linter configuration should live in the project and not in the editor.

I'm going to tackle #4 next but I'll get to this soon.

**Comment by nmccready** [comment]
Any progress on this?

**Comment by nmccready** [comment]
Looks like some code can be taken from [here](https://github.com/AtomLinter/linter-eslint/blob/2743bb07b4611f1c45f15b796d1a9c8244dbce45/src/worker-helpers.js#L73-L77)

**Comment by markwainwright** [comment]
@nmccready, @zacronos, @davibe, @asorije,

I'd still like to implement configuration improvements, but honestly I just don't have the bandwidth or interest right now to work on this project 😞.

We definitely need to move the configuration out of Atom and into a file in the project. The aims should be to allow the user to:
- Specify environments (currently in Atom config)
- Specify individual allowed globals (an example is `atom` in #14, which we've hardcoded for now)
- Configure unused and undefined errors separately – whether they are errors or warnings and even disabling one entirely (see #11)
- Allow function arguments that are unused in the function body (see #8)

The big question mark for me is how we do that:
1. Use an existing `.eslintrc` file. On the plus side, this would allow the user to configure all of the above. On the downside, the fact that we're using Eslint should be opaque to the user, so it isn't a very natural match.
2. Document extensions to `coffeelint.json` for each of the above. Certainly a lot more work than the above.
3. Look for a new file, specific to this project. `.coffeevarrc` or something. This is probably overkill.

Suggestions? Thoughts?

PRs very happily welcomed.

**Comment by zacronos** [comment]
Brainstorming here, and I haven't played with Eslint so I could be suggesting things that are inconvenient or even impossible.

Can we create define a new file, `.coffeevarrc` or something, and (for now) make it a passthrough of some sort, so it acts just like an `.eslintrc`?  This would leave open the possibility if necessary (at some later point) to add other options in the file that aren't supported by Eslint, somehow filtering them out before passing the rest on.  Eventually, if there was a good reason, the whole file format could be reworked -- I agree that is probably overkill, but at least the possibility would be there.

Documentation could be handled either with a link to the `.eslintrc` documentation and a note that says that it handles all the configuration options that are allowed in a `.eslintrc` file, or possibly a copy-paste of the documentation from Eslint.

**Comment by nmccready** [comment]
https://github.com/za-creature/coffeescope

**Comment by markwainwright** [comment]
@nmccready Sweet 😛

**Comment by astorije** [comment]
@markwainwright, I'm unclear, is this now possible?

I am dealing with a maaassive legacy project, and its asset pipeline makes extensive use of globals (like, a _ton_ of them!), so most are false positives, and I'd like a place where I could define globals, like it is possible in ESLint's configuration, for example.

Thanks!

**Comment by markwainwright** [comment]
@astorije No, it isn't currently possible to store globals in a config file with this plugin. You can set them in the plugin's configuration page in Atom though.

But as @nmccready pointed out, there's a new-ish coffeelint plugin, https://github.com/za-creature/coffeescope. While I haven't used it myself, it looks to cover all the functionality of this plugin and also allows globals to be set in its configuration.

**Comment by markwainwright** [comment]
@astorije No, it isn't currently possible to store globals in a config file with this plugin.

But as @nmccready pointed out, there's a new-ish coffeelint plugin, https://github.com/za-creature/coffeescope. While I haven't used it myself, it looks to cover all the functionality of this plugin and also allows globals to be set in its configuration. Might be worth a look!

**Comment by astorije** [comment]
@nmccready, @markwainwright, it seems like there is no Atom plugin for it yet, and my 2-minute search didn't show me a way to use it as a plugin of the coffeelint version the linter-coffeelint Atom package uses. Would you be aware of something? (Not that I'm trying to derail this topic/thread from your project, sorry!)

**Comment by nmccready** [comment]
@astorije did you try coffeescope? It extends eslint's capability in atom to lint coffeescript. All you need is coffeescope, eslint installed and the eslint plugin for atom. Done.

Can we lock this issue now?

**Comment by astorije** [comment]
I'm confused at how to set up `coffeescope` so that Atom's `linter-coffeelint` package can see it (you meant coffeelint, not ESLint, right?), but I guess this is the wrong place to ask for help :)

**Comment by nmccready** [comment]
You might be right coffee

```
apm ls
linter-coffeelint@1.3.1
```
