### ISSUE TITLE
[feature] Settings option to disable warning unused function arguments

### ISSUE THREAD

**Issue by nmccready** [markwainwright/atom-linter-coffee-variables#8]
Not sure if this is possible with eslint / jshint but warning for function args seems to be a contest with how my team works. I personally don't really mind it; but to compromise with them warning only non function argument vars would be useful.

**Comment by zacronos** [comment]
To elaborate, I consider it good coding practice to include all available parameters in the signature of a "handler" function (where the parameter list is defined by some external library, such as Node.js itself, Express.js, or lodash), even when some of those parameters are not being used.  It makes the code easier to maintain, when the developer comes back later (or maybe a new dev who isn't familiar with it) and can see what is available.

To support this coding practice, it would be very nice if the linter would have an option to ignore unused function parameters.  As it is, the only options for someone following this practice are to ignore the warnings (a bad habit) or turn off unused variable warnings altogether (not ideal).

**Comment by nmccready** [comment]
Closing as this new module works very well and makes this one not needed as it integrates with coffeelint directly.

https://github.com/za-creature/coffeescope

**Comment by binarykitchen** [comment]
@nmccready how do you use coffeescope in atom? it's not an atom plugin ...

**Comment by nmccready** [comment]
@binarykitchen you make coffeescope a dependency just like eslint in your node project. The you add in the coffeescope configs in the eslintrc. Essentially, you are extending and using eslintrc.

**Comment by nmccready** [comment]
Therefore you only need eslint atom plug in for it to work.

**Comment by binarykitchen** [comment]
i see, thanks
